=== Srbislav98/XML_i_web_servisi/dokumenti/xml i seme/obavestenjecir.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/obavestenjecir"
    xmlns:oba="http://www.ftn.uns.ac.rs/obavestenjecir">
    <xs:element name="obavestenje">
        <xs:complexType mixed="false">
            <xs:sequence>
                <xs:element name="naziv_organa">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string"/>
                                <xs:attribute name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sediste_organa">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property" type="xs:string"/>
                                <xs:attribute name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="broj_predmeta" type="xs:int" nillable="true"/>
                <xs:element name="datum" nillable="true">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute name="property" type="xs:string"/>
                                <xs:attribute name="datatype" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="podnosilac_zahteva" type="oba:tipPodnosilacZahteva"/>
                <xs:element name="naslov" type="xs:string"/>
                <xs:element name="uvid" type="oba:tipUvid"/>
                <xs:element maxOccurs="2" name="paragraf">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string"> </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="troskovi_detaljno" type="xs:string"/>
                <xs:element name="iznos_troskova" type="oba:tipIznosTroskova"/>
                <xs:element name="dostavljeno" type="oba:tipDostavljeno"/>
            </xs:sequence>
            <xs:attribute name="about" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="tipPodnosilacZahteva">
        <xs:sequence>
            <xs:element name="ime">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" type="xs:string"/>
                            <xs:attribute name="datatype" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="prezime">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" type="xs:string"/>
                            <xs:attribute name="datatype" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="naziv" type="xs:string"/>
            <xs:element name="adresa_podnosioca_zahteva">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="property" type="xs:string"/>
                            <xs:attribute name="datatype" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="tipUvid">
        <xs:sequence>
            <xs:element name="godina" type="xs:gYear" nillable="true"/>
            <xs:element name="opis_trazene_informacije" type="xs:string"/>
            <xs:element name="ime_dana" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Ponedeljak"/>
                        <xs:enumeration value="Utorak"/>
                        <xs:enumeration value="Sreda"/>
                        <xs:enumeration value="ÄŒetvrtak"/>
                        <xs:enumeration value="Petak"/>
                        <xs:enumeration value="Subota"/>
                        <xs:enumeration value="Nedelja"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="broj_sati" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="8"/>
                        <xs:maxInclusive value="21"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="pocetak_akcije" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:time">
                        <xs:minInclusive value="08:00:00"/>
                        <xs:maxInclusive value="20:00:00"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="kraj_akcije" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:time">
                        <xs:minInclusive value="09:00:00"/>
                        <xs:maxInclusive value="21:00:00"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="naziv_zgrade" type="xs:string"/>
            <xs:element name="naziv_ulice" type="xs:string"/>
            <xs:element name="broj_ulice" type="xs:int" nillable="true"/>
            <xs:element name="broj_kancelarije" type="xs:int" nillable="true"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="tipIznosTroskova">
        <xs:sequence>
            <xs:element name="kolicina_novca" type="xs:int" nillable="true"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="tipDostavljeno">
        <xs:sequence>
            <xs:element name="kojem_M._P._dostavlja" type="xs:string"/>
            <xs:element name="arhiva" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Srbislav98/XML_i_web_servisi/dokumenti/xml/obavestenjecir.xml
<?xml version="1.0" encoding="UTF-8"?>
<obavestenje xmlns="http://www.ftn.uns.ac.rs/obavestenjecir"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/obavestenjecir file:/C:/Users/Kssbc/Documents/GitHub/XML_i_web_servisi/dokumenti/xsd/obavestenjecir.xsd">
    <naziv_organa></naziv_organa>
    <sediste_organa></sediste_organa>
    <broj_predmeta>0</broj_predmeta>   
    <datum>2020-01-01</datum>
    <ime></ime>
    <prezime></prezime>
    <naziv></naziv>
    <adresa_podnosioca_zahteva></adresa_podnosioca_zahteva>
    
    <naslov>
        O B A V E Š T E Nj E
        o stavljanju na uvid dokumenta koji sadrži
        traženu informaciju i o izradi kopije
    </naslov>
    <uvid>
        Na osnovu člana 16. st. 1. Zakona o slobodnom pristupu informacijama od javnog značaja, postupajući po vašem zahtevu za slobodan pristup informacijama od 
        <godina>2020</godina>,  kojim ste tražili uvid u dokument/e sa informacijama o / u vezi sa: <opis_trazene_informacije></opis_trazene_informacije>obaveštavamo vas da dana 
        <ime_dana>Ponedeljak</ime_dana> , u <broj_sati>8</broj_sati> časova, odnosno u vremenu od <pocetak_akcije>08:00:00</pocetak_akcije> do <kraj_akcije>09:00:00</kraj_akcije>,
        u prostorijama organa u <naziv_zgrade></naziv_zgrade> ul. <naziv_ulice></naziv_ulice> br. <broj_ulice>0</broj_ulice> kancelarija br. <broj_kancelarije>0</broj_kancelarije>
        možete izvršiti uvid u dokument/e u kome je sadržana tražena informacija. 
    </uvid>
    <paragraf broj="1">
        Tom prilikom, na vaš zahtev, može vam se izdati i kopija dokumenta sa traženom informacijom.
    </paragraf>
    <paragraf broj="2">
        Troškovi su utvrđeni Uredbom Vlade Republike Srbije („Sl. glasnik RS“, br. 8/06), i to: kopija strane A4 formata iznosi 3 dinara, A3 formata 6 dinara, CD 35 dinara, diskete 20 dinara, DVD 40 dinara, audio-kaseta – 150 dinara, video-kaseta 300 dinara, pretvaranje jedne strane dokumenta iz fizičkog u elektronski oblik – 30 dinara.
    </paragraf>
    <iznos_troskova>
        Iznos ukupnih troškova izrade kopije dokumenta po vašem zahtevu iznosi <kolicina_novca>0</kolicina_novca> dinara i uplaćuje se na žiro-račun Budžeta Republike Srbije br. 840-742328-843-30, s pozivom na broj 97 – oznaka šifre opštine/grada gde se nalazi organ vlasti (iz Pravilnika o uslovima i načinu vođenja računa – „Sl. glasnik RS“, 20/07... 40/10). 
    </iznos_troskova>
    <dostavljeno>
        <kojem_M._P._dostavlja></kojem_M._P._dostavlja>
        <arhiva></arhiva>
    </dostavljeno>
    
</obavestenje>
