=== Srbislav98/XML_i_web_servisi/dokumenti/xsd/resenja.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.ftn.uns.ac.rs/resenja" xmlns:res="http://www.ftn.uns.ac.rs/resenja">

    <xs:element name="resenje">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="levo" type="res:TipLevo"/>
                <xs:element name="desno" type="res:TipDesno"/>
                <xs:element name="opis_zalbe" type="res:TipOpis_zalbe"/>
                <xs:element name="naslov" type="xs:string"/>
                <xs:element name="resenje_zalbe" type="xs:string"/>
                <xs:element name="podnaslov" type="xs:string"/>
                <xs:element name="obrazlozenja_zalbe" type="res:TipObrazlozenja_zalbe"/>
                <xs:element name="fusnota" type="xs:string"/>
                <xs:element name="poverenik" type="res:TipPoverenik"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TipLevo">
        <xs:sequence>
            <xs:element name="broj_zalbe">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{3}-\d{2}-\d{4}/\d{4}-\d{2}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TipDesno">
        <xs:sequence>
            <xs:element name="datum_zalbe">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{2}[.]\d{2}[.]\d{4}."/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="TipOpis_zalbe">
        <xs:sequence>
            <xs:element name="datum_zahteva">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{2}[.]\d{2}[.]\d{4}."/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TipObrazlozenja_zalbe">
        <xs:sequence>
            <xs:element name="razlog_podnosenja_zalbe" type="xs:string"/>
            <xs:element name="trazenje_odgovora_od_strane_optuzenog" type="xs:string"/>
            <xs:element name="odluka" type="xs:string"/>
            <xs:element name="dogadjaj" type="xs:string"/>
            <xs:element name="odgovor_na_dogadjaj" type="xs:string"/>
            <xs:element name="prekrsaj" type="res:TipPrekrsaj"/>
            <xs:element name="sta_optuzeni_mora_da_uradi" type="xs:string"/>
            <xs:element name="upustvo" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="TipPrekrsaj">
        <xs:sequence>
            <xs:element name="datum_zahteva">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{2}[.]\d{2}[.]\d{4}."/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="TipPoverenik">
        <xs:sequence>
            <xs:element name="ime_poverenika" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Srbislav98/XML_i_web_servisi/dokumenti/xml/prvoResenje.xml
<?xml version="1.0" encoding="UTF-8"?>
<resenje xmlns="http://www.ftn.uns.ac.rs/resenja"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/resenja file:/C:/Users/Kssbc/Documents/GitHub/XML_i_web_servisi/dokumenti/xsd/resenja.xsd">
    Rešenje kada je žalba osnovana – nalaže se:
    <levo>
        <broj_zalbe>071-01-1114/2020-03</broj_zalbe>
    </levo>
    <desno>
        <datum_zalbe>09.06.2020.</datum_zalbe>
    </desno>
    <opis_zalbe>
        Poverenik za informacije od javnog značaja i zaštitu podataka o ličnosti, u postupku po albi
        koju je izjavio AA, zbog nepostupanja Učiteljskog fakulteta u Prizrenu sa privremenim sedištem
        u Leposaviću, ul. Nemanjina bb, po njegovom zahtevu od <datum_zahteva>16.04.2020.</datum_zahteva> godine za pristup
        informacijama od javnog značaja, na osnovu člana 35. stav 1. tačka 5. Zakona o slobodnom pristupu
        informacijama od javnog značaja („Sl. glasnik RS“, br. 120/04, 54/07, 104/09 i 36/10), a u vezi sa
        članom 4. tačka 22. Zakona o zaštiti podataka o ličnosti („Sl. glasnik RS“, broj 87/18), kao i člana
        23. i člana 24. stav 4. Zakona o slobodnom pristupu informacijama od javnog značaja i člana 173.
        stav 2. Zakona o opštem upravnom postupku („Sl. glasnik RS“, br. 18/2016 i 95/2018-autentično
        tumačenje), donosi 
    </opis_zalbe>
    <naslov>
        R E Š E Nj E 
    </naslov>
    
        <resenje_zalbe>
            Nalaže se Učiteljskom fakultetu u Prizrenu sa privremenim sedištem u Leposaviću, da
            bez odlaganja, a najkasnije u roku od pet dana od dana prijema ovog rešenja, obavesti AA, da li
            poseduje tražene informacije odnosno dokument u kome su iste sadržane, i to: Ugovor o radu koji
            je kao poslednji potpisan između tog Fakulteta i BB, te da mu, ukoliko takav dokument poseduje
            dostavi kopiju istog elektronskom poštom na adresu … ili poštom, s tim što će pre dostavljanja
            zaštititi i učiniti nedostupnim podatke o ličnosti kojima bi se povredilo pravo na privatnost
            lica na koje se informacije odnose, kao što su: adresa stanovanja, lični matični broj građana, ime
            oca, radni staž, prosečna ocena studiranja i sl. ukoliko su takvi podaci sadržani u traženom
            dokumentu. 
            O izvršenju rešenja Učiteljski fakultet u Prizrenu sa privremenim sedištem u
            Leposaviću, će obavestiti Poverenika u roku od sedam dana od prijema ovog rešenja.
        </resenje_zalbe>
    
    <podnaslov>O b r a z l o ž e nj e</podnaslov>
    <obrazlozenja_zalbe>
        <razlog_podnosenja_zalbe>
            AA, kao tražilac informacija, izjavio je dana 07.05.2020. godine žalbu Povereniku, zbog
            nepostupanja Učiteljskog fakulteta u Prizrenu sa privremenim sedištem u Leposaviću po
            njegovom zahtevu od 16.04.2020. godine za pristup informacijama od javnog značaja i u prilogu
            dostavio kopiju istog.
        </razlog_podnosenja_zalbe>
        <trazenje_odgovora_od_strane_optuzenog>
            Postupajući po žalbi, Poverenik je dana 11.05.2020. godine uputio istu na izjašnjenje
            Učiteljskom fakultetu u Prizrenu sa privremenim sedištem u Leposaviću, kao organu vlasti u
            smislu člana 3. Zakona o slobodnom pristupu informacijama od javnog značaja i zatražio da se
            izjasni o navodima žalbe, posebno o razlozima nepostupanja u zakonskom roku po podnetom zahtevu
            u skladu sa odredbama člana 16. st.1-9. ili st. 10. Zakona, ostavljajući rok od osam dana, povodom
            čega nije dobio odgovor.
            
        </trazenje_odgovora_od_strane_optuzenog>
        <odluka>
            Po razmatranju žalbe i ostalih spisa ovog predmeta, doneta je odluka kao u dispozitivu
            rešenja iz sledećih razloga:
        </odluka>
        <dogadjaj>
            Uvidom u spise predmeta utvrđeno je da je AA, dana 16.04.2020. godine, podneo Učiteljskom
            fakultetu u Prizrenu sa privremenim sedištem u Leposaviću, zahtev za pristup informacijama
            od javnog značaja, elektronskom poštom, kojim je tražio informacije od javnog značaja, bliže
            navedene u stavu I dispozitiva ovog rešenja.
        </dogadjaj>
        <odgovor_na_dogadjaj>
            Takođe je uvidom u spise predmeta utvrđeno da po zahtevu žalioca od 16.04.2020. godine,
            organ vlasti nije postupio, što je bio dužan da učini bez odlaganja, a najkasnije u roku od 15 dana
            od prijema zahteva te da žalioca, u smislu člana 16. stav 1. Zakona o slobodnom pristupu 
            informacijama od javnog značaja, obavesti da li poseduje tražene informacije i da mu, ukoliko
            iste poseduje, stavi na uvid dokument koji iste sadrži odnosno izda mu ili dostavi kopiju
            dokumenta u kome su tražene informacije sadržane, ili da u suprotnom donese rešenje o odbijanju
            zahteva, u smislu stava 10. istog člana.
        </odgovor_na_dogadjaj>
   
        <prekrsaj>
            Imajući u vidu da organ vlasti po zahtevu žalioca od <datum_zahteva>16.04.2020.</datum_zahteva> godine nije postupio u
            skladu sa navedenim odredbama Zakona o slobodnom pristupu informacijama od javnog značaja, a
            da nije opravdao razloge nepostupanja po podnetom zahtevu, Poverenik je u postupku po žalbi, na
            osnovu člana 23. i člana 24. st. 1. i 4. Zakona o slobodnom pristupu informacijama od javnog
            značaja i člana 173. st. 2. Zakona o opštem upravnom postupku, odlučio kao u stavu I dispozitiva
            ovog rešenja, našavši da je žalba osnovana, odnosno da je nesporno pravo žalioca na tražene
            informacije u smislu člana 5. Zakona o slobodnom pristupu informacijama od javnog značaja, po
            kome svako ima pravo da mu bude saopšteno da li organ vlasti poseduje ili mu je dostupna određena
            informacija od javnog značaja, kao i da mu se informacija, ukoliko je u posedu organa, učini
            dostupnom, na način kako je to naloženo u stavu I dispozitiva ovog rešenja, što je u skladu sa
            odredbom člana 12. Zakona o slobodnom pristupu informacijama od javnog značaja, koja predviđa
            mogućnost izdvajanja tražene informacije od javnog značaja od ostalih informacija sadržanih u
            dokumentu u koje organ vlasti nije dužan da tražiocu omogući uvid, jer bi se dostupnošću tim
            informacijama povredilo pravo na privatnost i zaštitu podataka o ličnosti lica na koja se
            tražene informacije odnose..
        </prekrsaj>
        <sta_optuzeni_mora_da_uradi>
            Učiteljski fakultet u Prizrenu sa privremenim sedištem u Leposaviću, je dužan da o
            izvršenju rešenja iz stava I dispozitiva, obavesti Poverenika u skladu sa članom 24. stav 3. Zakona
            o slobodnom pristupu informacijama od javnog značaja. 
        </sta_optuzeni_mora_da_uradi>
        <upustvo>
            Uputstvo o pravnom sredstvu:
            Protiv ovog rešenja nije dopuštena žalba već se, u skladu sa Zakonom o upravnim
            sporovima, može pokrenuti upravni spor tužbom Upravnom sudu u Beogradu, u roku od 30 dana od
            dana prijema rešenja. Taksa na tužbu iznosi 390,00 dinara.
        </upustvo>
    </obrazlozenja_zalbe>
    <fusnota>
        Poverenik za informacije od javnog značaja i zaštitu podataka o ličnosti
        Informator o radu 31.08.2020.godine
    </fusnota>
    <poverenik>
        POVERENIK
        <ime_poverenika>
            Milan Marinović 
        </ime_poverenika>
    </poverenik>
</resenje>
